### ISSUE TITLE
Sub-initiative should allow non-positive values

### ISSUE THREAD

**Issue by palebedev** [010011001011101/AntiMunchLite#1]
It appears convenient to put creature's initiative modifier directly into sub-initiative field, as it is used to sort in descending order. At the moment any non-positive value is autocorrected to 1, preventing such usage if you have slowpokes in your encounter.

**Comment by 010011001011101** [comment]
Hm. As planned, sub-initiative field have two purposes:
- Order combatants actions before combat when they have same initiative. And it’s not always question of modifiers.
- Manage initiative shifts like "I move initiative just after/before <combatant name>".

I agree, initial placing initiative modifier in sub-initiative field can help for first purpose, but I never thougt about it this way ))

Unfortunately I don’t think I can fix it so easily... Sub-initiative is part of serializing model, that is used for save/load, and it have uint type. And because serializing is binary all previous saves will be wasted if I just change it to int. One-version saves converter will require duplicating core model and it’s too oversized for such issue. Soo... let’s don’t forget about it in Full AntiMunch! Not Lite!
